# ===================================================================
# datasource config
# druid alibaba database connection pool
# ===================================================================
server:
  port: 8087

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/gnc_1.0.0?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
      username: root
      password: gnC-1958
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
  jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
        generate-ddl: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
  redis:
    database: 0
    host: 127.0.0.1
    password: passwd_redis
    port: 6397
    timeout: 5000
    pool:
      max-wait: -1
      max-active: 1024
      max-idle: 200
      min-idle: 1

orders:
  auto:
    close-time: 1  # 订单24小时自动关闭
    receive-time: 14 # 订单14天自动确认收货

apk-server:
  url: https://api.gncfs.com