# ===================================================================
# datasource config
# druid alibaba database connection pool
# ===================================================================
spring:
  datasource:
      url: jdbc:mysql://192.168.1.188:3306/gnc_dev_point?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
      username: root
      password: local-2018
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
  jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: false
      generate-ddl: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
  redis:
    database: 2
    host: 192.168.1.188
    password: passwd_redis
    port: 6397
    timeout: 5000
    pool:
      max-wait: -1
      max-active: 1024
      max-idle: 200
      min-idle: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: liegou
    password: admin

orders:
  auto:
    close-time: 1  # 订单24小时自动关闭
    receive-time: 14 # 订单14天自动确认收货

apk-server:
  url: http://192.168.1.188:8787